APP_NAME: "server"
APP_PORT: "8008"

DB_DRIVER: "postgres"
DB_HOST: "localhost"
DB_PORT: 5432
DB_NAME: "poc_projectP"
DB_USER: "postgres"
DB_PASSWORD: ""
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
MIGRATION_PATH: "./migrations"

#JWT Configuration
JWT_SECRET_KEY: "my_secret_key"
TOKEN_EXPIRY: 30 #Minutes